import { Figtree, Macondo } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/UI/Header";

const figTree = Figtree({
  variable: "--font-figtree",
  subsets: ["latin"],
});

const macondo = Macondo({
  weight: ["400"],
  // variable: "--font-figtree",
  subsets: ["latin"],
});

export const metadata = {
  title: "fs04-v02",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${macondo.className} antialiased bg-black`}>
        <Header />
        <main className="grid gap-24 mb-24">{children}</main>
      </body>
    </html>
  );
}
